# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch


# Create random tensor

import torch

random_torch = torch.rand(7, 7)

random_torch.shape

print(random_torch)


tensor([[0.7206, 0.6881, 0.7198, 0.1913, 0.1724, 0.7022, 0.2684],
        [0.9735, 0.8733, 0.0590, 0.8831, 0.1463, 0.8851, 0.7447],
        [0.4127, 0.1483, 0.9654, 0.7744, 0.4936, 0.0608, 0.8503],
        [0.5829, 0.8661, 0.7314, 0.6293, 0.4698, 0.3697, 0.9921],
        [0.8348, 0.1923, 0.7914, 0.8645, 0.4097, 0.8268, 0.0929],
        [0.4846, 0.7748, 0.8185, 0.1418, 0.0712, 0.3466, 0.0079],
        [0.3621, 0.1682, 0.1850, 0.5299, 0.2715, 0.8140, 0.1015]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor

# Perform matrix multiplication

random_torch2 = torch.rand(1, 7)

random_torch , random_torch2

transposeOfTorch = random_torch2.T

torch.matmul(random_torch, transposeOfTorch)


tensor([[0.8231],
        [1.5152],
        [2.0486],
        [1.9974],
        [1.4347],
        [0.4808],
        [0.8439]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed


# Create two random tensors


# Matrix multiply tensors

import random

SEED = 0

torch.random.manual_seed(SEED)
rand2 = torch.rand(7, 1)

rand2


tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU

device = "cuda" if torch.cuda.is_available() else "cpu"


random_cuda = torch.rand(2, 3, device=device)

random_cuda



tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [31]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU

print(f"Device : {device}")

torch.manual_seed(1234)
rand1 = torch.rand(2, 3)

torch.manual_seed(1234)
rand2 = torch.rand(2, 3)

rand1 = rand1.to(device)
rand2 = rand2.to(device)


rand1, rand2


Device : cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [37]:
# Perform matmul on tensor_A and tensor_B

x = torch.matmul(rand1, rand2.T)

print(x, x.size())

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [38]:
# Find max

# Find min

x.min() , x.max()


(tensor(0.2161, device='cuda:0'), tensor(0.6287, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [39]:
# Find arg max


# Find arg min

x.argmax(), x.argmin()


(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [43]:
# Set seed

SEED = 7


# Create random tensor

torch.manual_seed(SEED)
rand1 = torch.rand(1, 1, 1, 10)


# Remove single dimensions

remove1 = rand1.squeeze()



# Print out tensors and their shapes

print(rand1, rand1.shape)
print(remove1, remove1.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
